global:
  scrape_interval: 3s

  external_labels:
    monitor: 'example-app'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'example'

    dns_sd_configs:
      - names: ['app']
        port: 5000
        type: A
        refresh_interval: 5s

  - job_name: 'student_svc'
    scrape_interval: 5s

    static_configs:
      - targets: ['student_svc:15000']
